version: "3.2"
volumes:
  mysql-data-volume:
  backend-static-volume:

services:
  backend:
    build: ./restful_backend/
    environment:
      DATABASE_NAME: rishi
      MYSQL_USER: root
      MYSQL_PWD: 66666666
      MYSQL_HOST: mysql
    volumes:
      - backend-static-volume:/app/backend/static
    ports:
      - 8000
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=325058560
    environment:
      MYSQL_ROOT_PASSWORD: 66666666
      MYSQL_DATABASE: rishi
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    volumes:
      - mysql-data-volume:/var/lib/mysql

  nginx:
    build: ./
    links:
      - backend
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - backend-static-volume:/app/backend/static
    ports:
      - 2000:80
    environment:
      NODE_ENV: production

  scheduler:
    build:
      context: ./runner
      dockerfile: Dockerfile_scheduler
