# Generated by Django 3.1.2 on 2020-11-11 06:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import django.utils.timezone
import picklefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the max length is 32, composed with "A-Za-z0-9_"', max_length=32, verbose_name='dataset name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='generate uuid by uuid1 algorithm', verbose_name='dataset uuid')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, help_text='the time at which the user uploaded the data; auto-generated', verbose_name='creation time')),
                ('upload', models.FileField(upload_to='uploads', verbose_name='data file')),
                ('related_user', models.ForeignKey(help_text='The user this dataset belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="the max length is 32, composed with 'A-Za-z0-9_'", max_length=32, verbose_name='job identifier for user')),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Uncomitted'), (2, 'Comitted'), (3, 'Done'), (4, 'Exception')], default=0)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, help_text='the time at which the user created the project; auto-generated', verbose_name='creation time')),
                ('groupby_indexs', models.CharField(default=None, max_length=256, null=True, validators=[django.core.validators.int_list_validator])),
                ('target_indexs', models.CharField(default=None, max_length=256, null=True, validators=[django.core.validators.int_list_validator])),
                ('timestamp_indexs', models.CharField(default=None, max_length=256, null=True, validators=[django.core.validators.int_list_validator])),
                ('related_data', models.ForeignKey(help_text='The data this job hold', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='project.dataset')),
                ('related_user', models.ForeignKey(help_text='The user this job belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_key', models.CharField(default=None, max_length=256, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Uncomitted'), (2, 'Comitted'), (3, 'Done'), (4, 'Exception')], default=0)),
                ('feature_indexs', models.CharField(default=None, max_length=256, null=True, validators=[django.core.validators.int_list_validator])),
                ('related_data', models.ForeignKey(help_text='The data this series connect', on_delete=django.db.models.deletion.CASCADE, related_name='series', to='project.dataset')),
                ('related_job', models.ForeignKey(help_text='The job that contains the series', on_delete=django.db.models.deletion.CASCADE, related_name='series', to='project.job')),
            ],
        ),
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=django.utils.crypto.get_random_string, help_text="the reasonable length is 8-32, composed with 'A-Za-z0-9_", max_length=32, verbose_name='name specified by user')),
                ('model_file', picklefield.fields.PickledObjectField(editable=False)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, help_text='the time when model created; auto-generated', null=True, verbose_name='the create time of model')),
                ('related_series', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='predictor', to='project.series')),
            ],
        ),
    ]
