# Generated by Django 3.1.2 on 2020-11-03 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the max length is 32, composed with "A-Za-z0-9_"', max_length=32, verbose_name='dataset name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='generate uuid by uuid1 algorithm', verbose_name='dataset uuid')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, help_text='the time at which the user uploaded the data; auto-generated', verbose_name='creation time')),
                ('upload', models.FileField(upload_to='uploads', verbose_name='data file')),
                ('related_user', models.ForeignKey(help_text='The user this dataset belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the max length is 32, composed with "A-Za-z0-9_"', max_length=32, verbose_name='project name')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, help_text='the time at which the user created the project; auto-generated', verbose_name='creation time')),
                ('related_data', models.ForeignKey(default='', help_text='The data this project hold', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.dataset')),
                ('related_user', models.ForeignKey(default='', help_text='The user this project belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
