# Generated by Django 3.1.3 on 2020-11-05 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='the time when model created; auto-generated', null=True, verbose_name='the create time of model'),
        ),
    ]
