# Generated by Django 3.1.2 on 2020-11-03 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='related_data',
            field=models.ForeignKey(help_text='The data this project hold', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.dataset'),
        ),
        migrations.AlterField(
            model_name='project',
            name='related_user',
            field=models.ForeignKey(help_text='The user this project belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(help_text="the max length is 32, composed with 'A-Za-z0-9_'", max_length=32, verbose_name='job identifier for user')),
                ('hyper_params', models.FileField(blank=True, null=True, upload_to='uploads/Config/HyperParams')),
                ('user_config', models.FileField(blank=True, null=True, upload_to='uploads/Config/UserConfig')),
                ('other_config', models.FileField(blank=True, null=True, upload_to='uploads/Config/OtherConfig')),
                ('job_status', models.IntegerField(choices=[(0, 'Uncomitted'), (1, 'Comitted'), (2, 'Job Done'), (3, 'Job Notified')], default=0)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, help_text='the time at which the user created the project; auto-generated', verbose_name='creation time')),
                ('related_project', models.ForeignKey(help_text='The project this job belongs', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='project.project')),
            ],
        ),
    ]
