# Generated by Django 3.1.2 on 2020-11-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='status',
        ),
        migrations.AddField(
            model_name='predictor',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Uncomitted'), (2, 'Comitted'), (3, 'Done'), (4, 'Exception')], default=0),
        ),
    ]
