# Generated by Django 3.1.2 on 2020-12-17 06:31

from django.db import migrations, models
import project.utils.dataset_utils


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201112_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='model_save',
            field=models.FileField(blank=True, null=True, upload_to=project.utils.dataset_utils.model_file_path, verbose_name='data file'),
        ),
    ]
