# Generated by Django 3.1.2 on 2020-11-03 21:28

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201104_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default=django.utils.crypto.get_random_string, help_text="the reasonable length is 8-32, composed with 'A-Za-z0-9_", max_length=32, verbose_name='name specified by user')),
                ('model_type', models.CharField(max_length=32)),
                ('model_perf', models.BinaryField(blank=True, help_text='calculated via test. may be optional', max_length=16, null=True, verbose_name='model performace record')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='uploads/Models/')),
                ('time_created', models.DateTimeField(blank=True, help_text='the time when model created; auto-generated', null=True, verbose_name='the create time of model')),
            ],
        ),
    ]
