# Generated by Django 3.1.2 on 2020-12-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_series_dataset'),
        ('project', '0003_predictor_model_save'),
    ]

    operations = [
    ]
