# Generated by Django 3.1.3 on 2020-11-04 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model_name',
            new_name='name',
        ),
    ]
