# Generated by Django 3.1.3 on 2020-11-04 02:52

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20201104_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hyper_params',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='other_config',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='user_config',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_perf',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, help_text='calculated via test. may be optional', null=True, verbose_name='model performace record'),
        ),
    ]
