# Generated by Django 3.1.2 on 2020-12-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_merge_20201217_1930'),
        ('project', '0004_merge_20201217_1920'),
    ]

    operations = [
    ]
