# Generated by Django 3.1.2 on 2020-12-17 15:21

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_merge_20201217_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Uncomitted'), (2, 'Comitted'), (3, 'Done'), (4, 'Exception')], default=0),
        ),
        migrations.AlterField(
            model_name='series',
            name='dataset',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
