# Generated by Django 3.1.3 on 2020-11-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20201104_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user_config',
            new_name='data_config',
        ),
    ]
