# Generated by Django 3.1.2 on 2020-10-22 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the max length is 32, composed with "A-Za-z0-9_"', max_length=32, verbose_name='project identifier for user')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, help_text='the time at which the user created the project; auto-generated', verbose_name='the creation time of project')),
                ('related_user', models.ForeignKey(help_text='The user this project belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the max length is 32, composed with "A-Za-z0-9_"', max_length=32, verbose_name='data identifier for user')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, help_text='the time at which the user uploaded the data; auto-generated', verbose_name='the creation time of data')),
                ('upload', models.FileField(upload_to='uploads', verbose_name='data file')),
                ('related_project', models.ForeignKey(help_text='dataset', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='project.project')),
            ],
        ),
    ]
