apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: worker
  labels:
    app: worker
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: worker
  template:
    metadata:
      labels:
        tier: worker
    spec:
      containers:
      - name: worker
        image: kalineid/worker
